/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Code;

/**
 *
 * @author Wasantha
 */
public class DirectorDashboard extends javax.swing.JFrame {

    /**
     * Creates new form StudentDashboard
     */
    public DirectorDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TimeTaButton = new javax.swing.JButton();
        MarkAttenButton = new javax.swing.JButton();
        ViewAttenButton = new javax.swing.JButton();
        ViewAnnouButton = new javax.swing.JButton();
        ViewStuInfoButton = new javax.swing.JButton();
        UploadAnnounButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Director Dashboard");

        TimeTaButton.setBackground(new java.awt.Color(51, 51, 255));
        TimeTaButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TimeTaButton.setForeground(new java.awt.Color(255, 255, 255));
        TimeTaButton.setText("View Time Table");
        TimeTaButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        TimeTaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TimeTaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeTaButtonActionPerformed(evt);
            }
        });

        MarkAttenButton.setBackground(new java.awt.Color(51, 51, 255));
        MarkAttenButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MarkAttenButton.setForeground(new java.awt.Color(255, 255, 255));
        MarkAttenButton.setText("Mark Attendance");
        MarkAttenButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        MarkAttenButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MarkAttenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarkAttenButtonActionPerformed(evt);
            }
        });

        ViewAttenButton.setBackground(new java.awt.Color(51, 51, 255));
        ViewAttenButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ViewAttenButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewAttenButton.setText("View Attendance");
        ViewAttenButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        ViewAttenButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewAttenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAttenButtonActionPerformed(evt);
            }
        });

        ViewAnnouButton.setBackground(new java.awt.Color(51, 51, 255));
        ViewAnnouButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ViewAnnouButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewAnnouButton.setText("View Announcement");
        ViewAnnouButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        ViewAnnouButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewAnnouButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAnnouButtonActionPerformed(evt);
            }
        });

        ViewStuInfoButton.setBackground(new java.awt.Color(51, 51, 255));
        ViewStuInfoButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ViewStuInfoButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewStuInfoButton.setText("View Student Information");
        ViewStuInfoButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        ViewStuInfoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewStuInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewStuInfoButtonActionPerformed(evt);
            }
        });

        UploadAnnounButton.setBackground(new java.awt.Color(51, 51, 255));
        UploadAnnounButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        UploadAnnounButton.setForeground(new java.awt.Color(255, 255, 255));
        UploadAnnounButton.setText("Upload Announcement");
        UploadAnnounButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        UploadAnnounButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UploadAnnounButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadAnnounButtonActionPerformed(evt);
            }
        });

        BackButton.setBackground(new java.awt.Color(51, 51, 255));
        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 255, 255));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MarkAttenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ViewAnnouButton, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ViewAttenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UploadAnnounButton, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ViewStuInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(TimeTaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BackButton)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewStuInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimeTaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MarkAttenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewAttenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewAnnouButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UploadAnnounButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TimeTaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeTaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeTaButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        DirectorLogin acd= new DirectorLogin();
        acd.show();
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void UploadAnnounButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadAnnounButtonActionPerformed
        SendAnnouncement acd= new  SendAnnouncement();
        acd.show();
        dispose();
    }//GEN-LAST:event_UploadAnnounButtonActionPerformed

    private void ViewStuInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewStuInfoButtonActionPerformed
        ViewStudentDetails acd= new ViewStudentDetails();
        acd.show();
        dispose();
    }//GEN-LAST:event_ViewStuInfoButtonActionPerformed

    private void MarkAttenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarkAttenButtonActionPerformed
        LCAttendenceMark acd= new  LCAttendenceMark();
        acd.show();
        dispose();
    }//GEN-LAST:event_MarkAttenButtonActionPerformed

    private void ViewAttenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAttenButtonActionPerformed
        ViewAttendenceLec acd= new  ViewAttendenceLec();
        acd.show();
        dispose();
    }//GEN-LAST:event_ViewAttenButtonActionPerformed

    private void ViewAnnouButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAnnouButtonActionPerformed
        ViewAnnouncement acd= new  ViewAnnouncement();
        acd.show();
        dispose();
    }//GEN-LAST:event_ViewAnnouButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DirectorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DirectorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DirectorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DirectorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DirectorDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton MarkAttenButton;
    private javax.swing.JButton TimeTaButton;
    private javax.swing.JButton UploadAnnounButton;
    private javax.swing.JButton ViewAnnouButton;
    private javax.swing.JButton ViewAttenButton;
    private javax.swing.JButton ViewStuInfoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
