/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Code;

/**
 *
 * @author Wasantha
 */
public class RegistrarDashboard extends javax.swing.JFrame {

    /**
     * Creates new form StudentDashboard
     */
    public RegistrarDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UploadLecButton = new javax.swing.JButton();
        MarkAttenButton = new javax.swing.JButton();
        ViewAttenButton = new javax.swing.JButton();
        ViewAnnouButton = new javax.swing.JButton();
        ViewStuInfoButton = new javax.swing.JButton();
        UpdateDeleteInforButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        UploadAnnounButton1 = new javax.swing.JButton();
        UpdateDeleteLecButton1 = new javax.swing.JButton();
        UploadInforButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Dashboard");

        UploadLecButton.setBackground(new java.awt.Color(51, 51, 255));
        UploadLecButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        UploadLecButton.setForeground(new java.awt.Color(255, 255, 255));
        UploadLecButton.setText("Upload Information Lectures");
        UploadLecButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        UploadLecButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UploadLecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadLecButtonActionPerformed(evt);
            }
        });

        MarkAttenButton.setBackground(new java.awt.Color(51, 51, 255));
        MarkAttenButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MarkAttenButton.setForeground(new java.awt.Color(255, 255, 255));
        MarkAttenButton.setText("Mark Attendance");
        MarkAttenButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        MarkAttenButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MarkAttenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarkAttenButtonActionPerformed(evt);
            }
        });

        ViewAttenButton.setBackground(new java.awt.Color(51, 51, 255));
        ViewAttenButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ViewAttenButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewAttenButton.setText("View Attendance");
        ViewAttenButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        ViewAttenButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewAttenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAttenButtonActionPerformed(evt);
            }
        });

        ViewAnnouButton.setBackground(new java.awt.Color(51, 51, 255));
        ViewAnnouButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ViewAnnouButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewAnnouButton.setText("View Announcement");
        ViewAnnouButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        ViewAnnouButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewAnnouButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAnnouButtonActionPerformed(evt);
            }
        });

        ViewStuInfoButton.setBackground(new java.awt.Color(51, 51, 255));
        ViewStuInfoButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ViewStuInfoButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewStuInfoButton.setText("View Student Information");
        ViewStuInfoButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        ViewStuInfoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewStuInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewStuInfoButtonActionPerformed(evt);
            }
        });

        UpdateDeleteInforButton.setBackground(new java.awt.Color(51, 51, 255));
        UpdateDeleteInforButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        UpdateDeleteInforButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateDeleteInforButton.setText("Update & Delete Information Students");
        UpdateDeleteInforButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        UpdateDeleteInforButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateDeleteInforButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDeleteInforButtonActionPerformed(evt);
            }
        });

        BackButton.setBackground(new java.awt.Color(51, 51, 255));
        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 255, 255));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        UploadAnnounButton1.setBackground(new java.awt.Color(51, 51, 255));
        UploadAnnounButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        UploadAnnounButton1.setForeground(new java.awt.Color(255, 255, 255));
        UploadAnnounButton1.setText("Upload Announcement");
        UploadAnnounButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        UploadAnnounButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UploadAnnounButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadAnnounButton1ActionPerformed(evt);
            }
        });

        UpdateDeleteLecButton1.setBackground(new java.awt.Color(51, 51, 255));
        UpdateDeleteLecButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        UpdateDeleteLecButton1.setForeground(new java.awt.Color(255, 255, 255));
        UpdateDeleteLecButton1.setText("Update & Delete Information Lectures");
        UpdateDeleteLecButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        UpdateDeleteLecButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateDeleteLecButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDeleteLecButton1ActionPerformed(evt);
            }
        });

        UploadInforButton1.setBackground(new java.awt.Color(51, 51, 255));
        UploadInforButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        UploadInforButton1.setForeground(new java.awt.Color(255, 255, 255));
        UploadInforButton1.setText("Upload Information Students");
        UploadInforButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        UploadInforButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UploadInforButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadInforButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MarkAttenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewAnnouButton, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewStuInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UploadInforButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ViewAttenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(UploadAnnounButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdateDeleteLecButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpdateDeleteInforButton, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(UploadLecButton, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(BackButton)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewStuInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UploadInforButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MarkAttenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewAttenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UploadAnnounButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewAnnouButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(UploadLecButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpdateDeleteInforButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpdateDeleteLecButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UploadLecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadLecButtonActionPerformed
        AddNewLecture acd= new AddNewLecture();
        acd.show();
        dispose();        
    }//GEN-LAST:event_UploadLecButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        AdminLogin acd= new AdminLogin();
        acd.show();
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void UpdateDeleteInforButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDeleteInforButtonActionPerformed
        UpdateDeleteInformation acd= new UpdateDeleteInformation();
        acd.show();
        dispose();
    }//GEN-LAST:event_UpdateDeleteInforButtonActionPerformed

    private void UpdateDeleteLecButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDeleteLecButton1ActionPerformed
        UpdateDeleteLecture acd= new UpdateDeleteLecture();
        acd.show();
        dispose();
    }//GEN-LAST:event_UpdateDeleteLecButton1ActionPerformed

    private void UploadInforButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadInforButton1ActionPerformed
        AddNewStudents acd= new AddNewStudents();
        acd.show();
        dispose();
    }//GEN-LAST:event_UploadInforButton1ActionPerformed

    private void ViewStuInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewStuInfoButtonActionPerformed
        ViewStudentDetails acd= new ViewStudentDetails();
        acd.show();
        dispose();
    }//GEN-LAST:event_ViewStuInfoButtonActionPerformed

    private void UploadAnnounButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadAnnounButton1ActionPerformed
       SendAnnouncement acd= new  SendAnnouncement();
        acd.show();
        dispose();
    }//GEN-LAST:event_UploadAnnounButton1ActionPerformed

    private void MarkAttenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarkAttenButtonActionPerformed
        LCAttendenceMark acd= new  LCAttendenceMark();
        acd.show();
        dispose();
    }//GEN-LAST:event_MarkAttenButtonActionPerformed

    private void ViewAttenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAttenButtonActionPerformed
        ViewAttendenceLec acd= new  ViewAttendenceLec();
        acd.show();
        dispose();
    }//GEN-LAST:event_ViewAttenButtonActionPerformed

    private void ViewAnnouButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAnnouButtonActionPerformed
        ViewAnnouncement acd= new  ViewAnnouncement();
        acd.show();
        dispose();
    }//GEN-LAST:event_ViewAnnouButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton MarkAttenButton;
    private javax.swing.JButton UpdateDeleteInforButton;
    private javax.swing.JButton UpdateDeleteLecButton1;
    private javax.swing.JButton UploadAnnounButton1;
    private javax.swing.JButton UploadInforButton1;
    private javax.swing.JButton UploadLecButton;
    private javax.swing.JButton ViewAnnouButton;
    private javax.swing.JButton ViewAttenButton;
    private javax.swing.JButton ViewStuInfoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
